@startuml
class ChuTich

class NhanVienChoVay

abstract class NV_DuyetVay{
    String ten, chucVu
    int hanMuc
    + NV_DuyetVay capTren(NV_DuyetVay capTren)
    + void duyetVay(int soTien)
}

NV_DuyetVay <|-- ChuTich
NV_DuyetVay <|-- NhanVienChoVay
NhanVienChoVay --> ChuTich : CapTren

@enduml