@startuml
skinparam classAttributeIconSize 0

package baitapA2 {
    class MyStringBuilder {
        - str : String

        + MyStringBuilder()
        + MyStringBuilder(initialStr: String)
        + addString(s: String) : MyStringBuilder
        + addFloat(f: float) : MyStringBuilder
        + addBool(b: boolean) : MyStringBuilder
        + toString() : String
    }

    class Main {
        + main(args: String[]) : void
    }
}

Main ..> MyStringBuilder : uses >
@enduml